# Generated by Django 5.1.2 on 2024-11-15 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_organizer_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('Venue_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Capacity', models.IntegerField()),
                ('Type', models.CharField(max_length=120)),
                ('Availability', models.BooleanField()),
                ('Pricing', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('Attendee_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Contact_Information', models.CharField(max_length=120)),
                ('TicketType', models.CharField(max_length=120)),
                ('Payment_Status', models.CharField(max_length=120)),
                ('EventRegistration_Date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
            ],
        ),
    ]
