# Generated by Django 5.1.2 on 2024-11-15 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_venue_attendee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('Ticket_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Ticket_Type', models.CharField(max_length=120)),
                ('Price', models.IntegerField()),
                ('Status', models.CharField(max_length=120)),
                ('DateOfIssue', models.DateField()),
                ('Attendee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attendee')),
                ('Event_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
            ],
        ),
    ]
